-- ReadFluent database setup. GENERATED by scripts/build-setup-sql.sh from
-- supabase/migrations/*.sql - edit those, not this file.
-- Paste the whole file into Supabase -> SQL Editor and press Run, once.

-- ===== 0001_init.sql =====
-- ReadFluent — initial schema
--
-- Three tables. Everything a reader does is stored on their device first
-- (CLAUDE.md, "Accounts and money": reading needs no account), so the server
-- holds only what has to outlive a device: who they are, what they pay for,
-- and a copy of their documents (0003_sync.sql) for their next phone. Content
-- (books, photos, audio) is not in the database at all; it is files in
-- object storage (SPEC.md §9).

create extension if not exists "pgcrypto";

-- ── users ────────────────────────────────────────────────────────────────────
-- Mirrors auth.users. The id is the SAME uuid, so upgrading an anonymous
-- device to a signed-in account (auth.updateUser / linking an identity) keeps
-- every foreign key intact: progress made before signing in is not lost.
-- `plan` and the three columns beside it are written only by the server
-- (0002_plan.sql), never by a reader.
create table if not exists public.users (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        text,
  is_anonymous boolean not null default true,
  -- Preferences a reader may write themselves (autoplay, slow audio, ...).
  settings     jsonb not null default '{}'::jsonb,
  plan         text not null default 'free',
  -- When the paid plan stops. Null means it does not: a subscription renewed
  -- elsewhere, or a hand-set grant.
  plan_until   timestamptz,
  -- Kept for reporting: which product (monthly / yearly) and RevenueCat's
  -- period type (TRIAL during a free trial).
  plan_product text,
  plan_period  text,
  created_at   timestamptz not null default now()
);

-- ── events ───────────────────────────────────────────────────────────────────
-- Product analytics (SPEC.md §12). Write-only from the client; read
-- server-side. user_id is nulled, not cascaded, when an account is deleted:
-- the counts survive, the person does not.
create table if not exists public.events (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references public.users(id) on delete set null,
  name       text not null,
  props      jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists events_name_created_idx on public.events (name, created_at);

-- ── row level security ───────────────────────────────────────────────────────
-- Rule: a reader reads and writes only their own rows.
alter table public.users  enable row level security;
alter table public.events enable row level security;

-- No insert policy on users: rows are created by the on_auth_user_created
-- trigger below, which is security definer. A client can never invent a user.
drop policy if exists users_select_own on public.users;
create policy users_select_own on public.users
  for select using (id = (select auth.uid()));

-- Broad on purpose: RLS cannot say "every column except plan". 0002_plan.sql
-- narrows it to the one column a reader may write, and puts a trigger behind it.
drop policy if exists users_update_own on public.users;
create policy users_update_own on public.users
  for update using (id = (select auth.uid())) with check (id = (select auth.uid()));

drop policy if exists events_insert_own on public.events;
create policy events_insert_own on public.events
  for insert with check (user_id = (select auth.uid()));

-- ── keeping public.users in step with auth.users ─────────────────────────────
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, is_anonymous)
  values (new.id, new.email, coalesce(new.is_anonymous, false))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Upgrading anonymous -> signed in keeps the same auth.users row, so mirror the
-- change rather than creating anything.
create or replace function public.handle_user_updated()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.users
     set email = new.email,
         is_anonymous = coalesce(new.is_anonymous, false)
   where id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
  after update of email, is_anonymous on auth.users
  for each row execute function public.handle_user_updated();

-- ===== 0002_plan.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- What a reader is paying for, and the rule that a reader cannot set it.
--
-- 0001's users_update_own policy is deliberately broad — a reader owns their
-- settings row and may write it freely — and RLS has no way to say "every
-- column except this one", so without what follows anybody with the anon key
-- and a devtools console could give themselves the paid plan:
--
--   update public.users set plan = 'full' where id = auth.uid();
--
-- Two defences, because one of them is quiet when it breaks.
--
--   1. Table privileges, narrowed to the one column a reader may write.
--      `revoke update (plan, plan_until)` on its own does NOTHING here:
--      PostgreSQL says outright that revoking a privilege from individual
--      columns has no effect while the role holds it on the whole table, and
--      Supabase grants exactly that to `authenticated` by default. So the
--      table-level right goes first, and only `settings` is granted back. A
--      column list also fails closed: a column added later is not writable
--      until somebody says it is.
--   2. A trigger that puts the old values back for anybody who is not the
--      service role. This is the guarantee: a later `grant all on public.users`
--      — the kind of line that gets pasted into a migration without much
--      thought — silently undoes the grant above, and nothing would say so.
--
-- Only the server, holding the service role key, moves anybody onto a plan.
-- It is the one thing in this schema that is worth money to forge. The first
-- readers can be moved by hand from the SQL editor, which is why the trigger
-- lets the database owner through.
-- ─────────────────────────────────────────────────────────────────────────────

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'users_plan_known'
  ) then
    alter table public.users
      add constraint users_plan_known check (plan in ('free', 'full'));
  end if;
end $$;

-- 1. The mechanism. The table-level right first, or the column list below is
--    decoration; then back only what a reader's own browser has any business
--    writing. `email` and `is_anonymous` are not here: they are mirrored from
--    auth.users by the security-definer triggers in 0001, which run as the
--    owner and do not need a grant.
revoke update on public.users from anon, authenticated;
grant update (settings) on public.users to authenticated;

-- 2. The guarantee.
-- NOT security definer — current_user must be the caller. Under security
-- definer it would be the function's owner every time and the guard would
-- never fire at all.
create or replace function public.users_plan_is_not_yours()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  /*
   * The service role is the server, which is the only thing allowed to sell
   * anything; the owner is a person at the SQL editor, which is how the first
   * readers are moved by hand. Everyone else gets their own row back with the
   * plan untouched.
   *
   * `current_user`, not the request's JWT claims. PostgREST sets that GUC and
   * nothing else does, so on a direct connection — the SQL editor, the table
   * editor, psql, pg_cron — it is unset, the guard fires, and a hand-grant
   * reports "UPDATE 1" while quietly reverting. Silent, and only findable by
   * selecting the row back.
   */
  if current_user not in ('service_role', 'postgres', 'supabase_admin') then
    new.plan := old.plan;
    new.plan_until := old.plan_until;
    new.plan_product := old.plan_product;
    new.plan_period := old.plan_period;
  end if;
  return new;
end $$;

drop trigger if exists users_plan_guard on public.users;
create trigger users_plan_guard
  before update on public.users
  for each row
  execute function public.users_plan_is_not_yours();

-- The app reads this rather than the raw column: a plan whose date has gone is
-- free again, and working that out in one place means a lapsed reader cannot
-- be paid-for on one screen and free on another. lib/plan.ts `effectivePlan`
-- is its TypeScript twin.
create or replace function public.effective_plan(u public.users)
returns text
language sql
stable
as $$
  select case
    when u.plan = 'full' and (u.plan_until is null or u.plan_until > now()) then 'full'
    else 'free'
  end
$$;

-- Finding everyone whose pass runs out in the next few days, which is the only
-- query this ever needs an index for.
create index if not exists users_plan_until on public.users (plan_until)
  where plan_until is not null;

-- ===== 0003_sync.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Sync: one row per local document.
--
-- The app is local-first. Reading progress, the words a reader has met and
-- their flashcards are written to the device and read from it; that is what
-- lets somebody read with no account and no network. This table is the copy
-- that follows a reader to their next device.
--
-- Documents, not relational tables. A document per row is lossless by
-- construction, needs no migration when a field is added, and gives conflict
-- resolution a natural unit: the document. What this is not: a merge engine.
-- Two devices editing the same document offline resolve last-write-wins, per
-- document, on `updated_at`. For a reading app that is the right trade — the
-- common case is one device at a time.
--
-- Who decides "newer", and who decides "since": `updated_at` is the client's
-- (what "newer" means), `synced_at` is the server's (what "since" means), set
-- by the guard trigger below. A pull is paged on `synced_at`, so a row written
-- offline hours ago can never be skipped by a device whose cursor has moved
-- past its client-stamped time. A push carrying an older copy than the row
-- already holds is refused by the database itself, because by the time a
-- client writes, whatever it read is already old.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.sync_docs (
  user_id    uuid not null references public.users(id) on delete cascade,
  -- The store this came from. Checked rather than free text so a typo in a
  -- client cannot quietly create a kind nothing ever reads back. Provisional:
  -- M8 (SPEC.md §10) wires the stores and may extend this list in a new
  -- migration.
  kind       text not null check (kind in ('progress','word','card','review')),
  -- The document's own id, as the app writes it. Text, because that is what
  -- the app's ids are ("<slug>/<level>-<length>" for progress, a headword for
  -- a word, ...).
  doc_id     text not null,
  -- The document verbatim. Null once deleted — the row is kept as a tombstone
  -- so the deletion travels; without it, a delete on one device is undone by
  -- the next pull from another.
  doc        jsonb,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  synced_at  timestamptz not null default now(),
  primary key (user_id, kind, doc_id)
);

-- Every pull is "my rows, changed since I last looked".
create index if not exists sync_docs_user_synced
  on public.sync_docs (user_id, synced_at);

alter table public.sync_docs enable row level security;

-- Own rows, all four verbs. Nothing here is public or shared.
drop policy if exists sync_docs_select_own on public.sync_docs;
create policy sync_docs_select_own on public.sync_docs
  for select using (user_id = (select auth.uid()));

drop policy if exists sync_docs_insert_own on public.sync_docs;
create policy sync_docs_insert_own on public.sync_docs
  for insert with check (user_id = (select auth.uid()));

drop policy if exists sync_docs_update_own on public.sync_docs;
create policy sync_docs_update_own on public.sync_docs
  for update using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

-- A delete is a tombstone (doc = null), not a DELETE, so this exists only for
-- "forget me": it lets the app wipe the server copy too rather than pulling it
-- all back on the next sync.
drop policy if exists sync_docs_delete_own on public.sync_docs;
create policy sync_docs_delete_own on public.sync_docs
  for delete using (user_id = (select auth.uid()));

/*
 * One trigger, both jobs, because they have an order and two triggers would
 * leave it to whichever name sorts first.
 *
 * Returning null from a BEFORE UPDATE skips that row and leaves what is there,
 * which is exactly "your copy is older than mine, keep mine". An upsert's
 * conflict path runs as an UPDATE, so this catches the push.
 *
 * Equal stamps are allowed through: a tie is the same write arriving twice,
 * and refusing it would mean a device that pushed, lost its answer and pushed
 * again could never repair the row.
 */
create or replace function public.sync_docs_before_write()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.updated_at < old.updated_at then
    return null;
  end if;
  -- Never the client's clock. This is the only thing pagination trusts.
  new.synced_at := now();
  return new;
end $$;

drop trigger if exists sync_docs_guard on public.sync_docs;
create trigger sync_docs_guard
  before insert or update on public.sync_docs
  for each row
  execute function public.sync_docs_before_write();
