/**
 * TEMPORARY, like the rest of lib/preview: the reader's template (the owner's, 1 Oct 2026) as data.
 * Five pages of Pride and Prejudice retold in Spanish at the three levels, each with the English
 * for the same sentences, three matched words, and a small dictionary of word cards. It is
 * compiled into the app, which CLAUDE.md forbids for real content; M1 replaces it with JSON
 * served from storage and the translation pipeline makes the rest.
 */
import type { ArtId } from "@/components/ObjectPhoto";
import type { LevelId } from "@/lib/content/limits";

/** What a word card shows: how to say it (where known) and one line of English — what it means and when it is used. */
export interface WordEntry { ph?: string; mean: string }
/** A word of the text and the word it matches in the translation: shown in the same colour in both. */
export interface KeyPair { w: string; en: string }
export interface TargetText { text: string; translation: string; keys: KeyPair[] }
export interface TargetPage { art: ArtId; bg: string; text: Record<LevelId, TargetText> }

export const SPANISH_LANG = "es" as const;

export const SPANISH_DICT: Record<string, WordEntry> = {
  "a": { mean: "to, at — shows where or who something goes to" },
  "admiración": { ph: "ahd-mee-rah-THYOHN", mean: "admiration — respect and liking" },
  "aguacero": { mean: "a heavy rain shower — a sudden downpour" },
  "alarmada": { ph: "ah-lar-MAH-dah", mean: "alarmed — suddenly very worried" },
  "alianza": { mean: "an alliance — a union, often by marriage" },
  "allí": { mean: "there — pointing to a place away from you" },
  "amable": { ph: "ah-MAH-bleh", mean: "friendly, kind — a polite, pleasant person" },
  "anticipando": { ph: "ahn-tee-thee-PAHN-doh", mean: "expecting — knowing ahead that it will happen" },
  "aparte": { mean: "apart, aside — standing away from the others" },
  "apenas": { mean: "barely, hardly — when something is only just true" },
  "apuesto": { mean: "handsome — said of a good-looking man" },
  "así": { mean: "so, like this — shows the way or the result" },
  "bailara": { mean: "danced — 'asked him to dance', after a request" },
  "baile": { ph: "BYE-leh", mean: "dance — a party where people dance" },
  "bailó": { mean: "danced — past tense of bailar, 'she danced'" },
  "barro": { mean: "mud — wet earth after rain" },
  "bastante": { ph: "bahs-TAHN-teh", mean: "enough, quite — 'bastante guapa' is pretty enough" },
  "bennet": { mean: "the Bennets — Elizabeth's family" },
  "bingley": { mean: "Mr Bingley — the friendly, rich newcomer" },
  "brillantes": { ph: "bree-YAHN-tes", mean: "bright, shining — eyes can be brillantes" },
  "buen": { mean: "good — short form of bueno before a masculine word" },
  "buenos": { mean: "good — plural, as in 'buenos días'" },
  "burló": { ph: "boor-LOH", mean: "mocked — 'se burló de' is made fun of" },
  "caballo": { ph: "kah-BAH-yoh", mean: "horse — 'a caballo' is on horseback" },
  "cada": { mean: "each, every — one by one, 'cada día'" },
  "cambio": { mean: "change — 'en cambio' means on the other hand" },
  "caminó": { ph: "kah-mee-NOH", mean: "walked — past tense of caminar" },
  "campos": { mean: "fields, countryside — open farmland" },
  "carácter": { mean: "character — a person's nature or manner" },
  "como": { mean: "as, like — also 'how' in questions" },
  "con": { mean: "with — together, 'con amigos'" },
  "correspondía": { mean: "matched, returned — a feeling answered in kind" },
  "crecía": { mean: "was growing — said of a feeling or a child" },
  "cumplió": { mean: "fulfilled — made a wish come true" },
  "dado": { mean: "given — in 'había dado', had given" },
  "darcy": { mean: "Mr Darcy — the rich, proud gentleman" },
  "de": { mean: "of, from — shows who it belongs to" },
  "decir": { mean: "to say, to tell — the everyday verb for speaking" },
  "demasiado": { mean: "too, too much — more than is good" },
  "dentro": { mean: "inside, within — 'dentro de ella' means inside her" },
  "desaliño": { mean: "untidiness — messy clothes or hair" },
  "desdén": { ph: "des-DEN", mean: "disdain — cold scorn for someone" },
  "deseo": { mean: "wish, desire — something you really want" },
  "despreció": { mean: "looked down on — treated as not good enough" },
  "detestara": { mean: "hated — felt a very strong dislike" },
  "dignos": { mean: "worthy — good enough for someone" },
  "dijo": { mean: "said — past tense of decir, 'he said'" },
  "ejercicio": { mean: "exercise — physical activity, like a long walk" },
  "el": { mean: "the — before a masculine word, 'el señor'" },
  "elizabeth": { mean: "Elizabeth Bennet — the heroine" },
  "ella": { mean: "she, her" },
  "embargo": { mean: "in 'sin embargo', meaning however" },
  "empujarlo": { mean: "to push him — here, to steer someone gently" },
  "en": { mean: "in, on, at — place or time" },
  "encantador": { mean: "charming — delightful and likeable" },
  "encuentro": { mean: "a meeting — when people come together" },
  "enferma": { ph: "en-FEHR-mah", mean: "ill, sick — said of a woman" },
  "entre": { mean: "between, among, through — 'entre el barro' is through the mud" },
  "envió": { mean: "sent — past tense of enviar" },
  "era": { mean: "was — past of ser, for what something was like" },
  "eran": { mean: "were — past of ser, plural" },
  "es": { mean: "is — present of ser, for who or what something is" },
  "esperando": { mean: "hoping, waiting — 'esperando lluvia' is hoping for rain" },
  "estaba": { mean: "was — past of estar, for a state or feeling" },
  "este": { mean: "this one — here, the man just mentioned" },
  "febril": { ph: "feh-BREEL", mean: "feverish — with a high temperature" },
  "frecuentemente": { ph: "freh-kwen-teh-MEN-teh", mean: "often — a formal way to say many times" },
  "frío": { mean: "cold — also 'cold and unfriendly'" },
  "fue": { mean: "was, went — past of ser (or ir)" },
  "grado": { mean: "in 'de buen grado', meaning gladly" },
  "guapa": { ph: "GWAH-pah", mean: "pretty, good-looking — said of a woman, casual" },
  "gustaba": { ph: "goos-TAH-bah", mean: "was pleasing — 'le gustaba' is he or she liked" },
  "hablar": { mean: "to speak, to talk" },
  "había": { mean: "had — helper verb, 'había nacido' is had been born" },
  "hacia": { mean: "toward — shows direction" },
  "hasta": { mean: "until, as far as — 'hasta Netherfield'" },
  "hecho": { mean: "made, done — 'había hecho que' is had made" },
  "hermana": { mean: "sister" },
  "hermanas": { ph: "er-MAH-nahs", mean: "sisters" },
  "hermano": { mean: "brother" },
  "hermosa": { ph: "er-MOH-sah", mean: "beautiful — stronger and more formal than guapa" },
  "humor": { mean: "mood, humour — 'buen humor' is good spirits" },
  "huésped": { mean: "guest — someone staying in another's home" },
  "ilustre": { mean: "distinguished — of high standing" },
  "jane": { mean: "Jane Bennet — Elizabeth's gentle older sister" },
  "la": { mean: "the (feminine), or 'her'" },
  "le": { mean: "to him, to her — who something is given or told to" },
  "les": { mean: "to them — plural of le" },
  "llegó": { mean: "arrived — past tense of llegar" },
  "llovió": { ph: "yoh-BYOH", mean: "rained — past of llover, 'it rained'" },
  "lluvia": { mean: "rain" },
  "lo": { mean: "it, him — stands in for a thing or a man" },
  "los": { mean: "the — plural, before masculine words" },
  "madre": { mean: "mother" },
  "meryton": { mean: "Meryton — the town where the dance is held" },
  "millas": { ph: "MEE-yahs", mean: "miles — an old English measure of distance" },
  "minutos": { mean: "minutes" },
  "miraban": { mean: "were looking at — past of mirar" },
  "mojados": { mean: "wet — soaked through" },
  "mucho": { mean: "a lot, much" },
  "muy": { mean: "very — comes before an adjective" },
  "más": { mean: "more — 'más rico' is richer" },
  "mí": { mean: "me — after a preposition, 'para mí'" },
  "nacido": { mean: "born — 'había nacido' is had been born (here, had grown)" },
  "nadie": { mean: "nobody, anyone — 'con nadie' is with anyone" },
  "netherfield": { mean: "Netherfield — Mr Bingley's country house" },
  "no": { mean: "no, not — makes a sentence negative" },
  "noche": { mean: "night, evening" },
  "notó": { mean: "noticed — past tense of notar" },
  "obligada": { ph: "oh-blee-GAH-dah", mean: "forced — made to do something" },
  "ofensa": { mean: "an insult, an offence" },
  "ojos": { mean: "eyes" },
  "olvidó": { ph: "ol-bee-DOH", mean: "forgot — past tense of olvidar" },
  "orgulloso": { ph: "or-goo-YOH-soh", mean: "proud — often a little too proud of yourself" },
  "oyó": { ph: "oh-YOH", mean: "heard — past tense of oír, 'she heard'" },
  "palabra": { mean: "word" },
  "para": { mean: "for, to, in order to — 'para mí' is for me" },
  "pensaban": { ph: "pen-SAH-bahn", mean: "were thinking, thought — past of pensar" },
  "permaneció": { mean: "stayed, remained — past of permanecer" },
  "pero": { mean: "but" },
  "pidió": { mean: "asked for — past tense of pedir" },
  "pocos": { mean: "few — 'en pocos minutos' is in a few minutes" },
  "por": { mean: "for, by, because of — 'por su hermana'" },
  "preocupada": { ph: "preh-oh-koo-PAH-dah", mean: "worried — said of a woman" },
  "pueblo": { mean: "town, village" },
  "puso": { mean: "put, became — 'se puso enferma' is became ill" },
  "que": { mean: "that, who, which — joins parts of a sentence" },
  "quedarse": { ph: "keh-DAR-seh", mean: "to stay — remain in one place" },
  "resentimiento": { ph: "reh-sen-tee-MYEN-toh", mean: "resentment — a bitter feeling that stays" },
  "rico": { mean: "rich — also 'tasty' about food" },
  "rio": { mean: "laughed — past tense of reír" },
  "sala": { mean: "room, hall — a big room full of people" },
  "satisfacción": { mean: "satisfaction — a pleased feeling" },
  "se": { mean: "himself, herself — 'se puso' is got, became" },
  "secreta": { mean: "secret — hidden from others" },
  "semilla": { mean: "seed — here, a small beginning of a feeling" },
  "sereno": { mean: "calm, serene" },
  "señor": { mean: "Mr, sir, gentleman" },
  "señora": { mean: "Mrs, lady" },
  "señorita": { mean: "Miss, young lady" },
  "silencio": { mean: "silence" },
  "sin": { mean: "without — 'sin embargo' means however" },
  "sintió": { mean: "felt — past of sentir; 'se sintió' is found himself" },
  "soportó": { mean: "put up with, bore — past tense of soportar" },
  "sorprendido": { mean: "surprised" },
  "su": { mean: "his, her, their — 'su hermana' is her sister" },
  "sucio": { ph: "SOO-thyoh", mean: "dirty — not clean" },
  "sus": { mean: "his, her, their — plural" },
  "sílaba": { mean: "syllable — one beat of a word" },
  "tentarlo": { mean: "to tempt him" },
  "toda": { mean: "all, whole — 'toda la noche' is all night" },
  "todos": { mean: "everyone, all — 'a todos' is to everyone" },
  "tolerable": { ph: "toh-leh-RAH-bleh", mean: "bearable — just good enough, no more" },
  "tramaron": { ph: "trah-MAH-rohn", mean: "plotted — made a secret plan together" },
  "tres": { mean: "three" },
  "tuvo": { mean: "had — past of tener; 'tuvo que' is had to" },
  "un": { mean: "a, an — before a masculine word" },
  "una": { mean: "a, an — before a feminine word" },
  "velado": { mean: "veiled, hidden — not said openly" },
  "ver": { mean: "to see — 'para ver a Jane' is to see Jane" },
  "vestido": { mean: "dress" },
  "vigor": { ph: "bee-GOR", mean: "energy, strength — a lively, healthy glow" },
  "vio": { mean: "saw — past tense of ver" },
  "visitaba": { mean: "used to visit — past of visitar" },
  "y": { mean: "and" },
  "él": { mean: "he, him — the accent marks a person" },
};

export const SPANISH_PAGES: TargetPage[] = [
  {
    art: "candle", bg: "#2f7f93",
    text: {
      A1A2: {
        text: "En el baile, el señor Bingley era amable, pero el señor Darcy era orgulloso.",
        translation: "At the dance, Mr Bingley was friendly, but Mr Darcy was proud.",
        keys: [{ w: "baile", en: "dance" }, { w: "amable", en: "friendly" }, { w: "orgulloso", en: "proud" }],
      },
      B1B2: {
        text: "En el baile de Meryton, el señor Bingley fue amable y bailó con Jane. El señor Darcy era rico y apuesto, pero era demasiado orgulloso para hablar con nadie.",
        translation: "At the dance in Meryton, Mr Bingley was friendly and danced with Jane. Mr Darcy was rich and handsome, but he was too proud to talk to anyone.",
        keys: [{ w: "baile", en: "dance" }, { w: "amable", en: "friendly" }, { w: "orgulloso", en: "proud" }],
      },
      C1C2: {
        text: "En el baile de Meryton, Bingley fue amable y encantador, y bailó toda la noche. Darcy, más rico y más apuesto, permaneció aparte en un frío silencio. En pocos minutos, su carácter orgulloso había hecho que toda la sala lo detestara.",
        translation: "At the dance in Meryton, Bingley was friendly and charming, and he danced all evening. Darcy was richer and handsomer, yet he stood apart in cold silence. Within minutes, his proud manner had made the whole room dislike him.",
        keys: [{ w: "baile", en: "dance" }, { w: "amable", en: "friendly" }, { w: "orgulloso", en: "proud" }],
      },
    },
  },
  {
    art: "fan", bg: "#e8b5c2",
    text: {
      A1A2: {
        text: "Elizabeth oyó a Darcy decir: \"Ella no es bastante guapa para mí.\"",
        translation: "Elizabeth heard Mr Darcy say, \"She is not beautiful enough for me.\"",
        keys: [{ w: "oyó", en: "heard" }, { w: "guapa", en: "beautiful" }, { w: "bastante", en: "enough" }],
      },
      B1B2: {
        text: "El señor Darcy dijo que Elizabeth no era bastante hermosa para él. Ella oyó cada palabra, y se rio, pero no lo olvidó.",
        translation: "Mr Darcy said that Elizabeth was not beautiful enough for him. She heard every word, and she laughed, but she did not forget.",
        keys: [{ w: "hermosa", en: "beautiful" }, { w: "oyó", en: "heard" }, { w: "olvidó", en: "forget" }],
      },
      C1C2: {
        text: "Bingley le pidió a Darcy que bailara con Elizabeth, pero este la despreció: apenas tolerable, dijo, y no lo bastante hermosa para tentarlo. Elizabeth oyó cada sílaba y soportó la ofensa con buen humor. Sin embargo, dentro de ella había nacido una semilla de resentimiento, y no lo olvidó.",
        translation: "Urged by Bingley to dance with Elizabeth, Darcy dismissed her as barely tolerable and not handsome enough to tempt him. Elizabeth overheard every syllable and bore the insult with good humour. Yet within her a seed of resentment had been planted, and she did not forget.",
        keys: [{ w: "tolerable", en: "tolerable" }, { w: "resentimiento", en: "resentment" }, { w: "olvidó", en: "forget" }],
      },
    },
  },
  {
    art: "letter", bg: "#efd47f",
    text: {
      A1A2: {
        text: "A todos les gustaba el señor Bingley, pero sus hermanas pensaban que los Bennet no eran bastante buenos.",
        translation: "Everyone liked Mr Bingley, but his sisters thought the Bennets were not good enough.",
        keys: [{ w: "gustaba", en: "liked" }, { w: "hermanas", en: "sisters" }, { w: "pensaban", en: "thought" }],
      },
      B1B2: {
        text: "A todos en el pueblo les gustaba el señor Bingley, y él visitaba frecuentemente a Jane. Pero sus hermanas pensaban que los Bennet no eran dignos de su hermano.",
        translation: "Everyone in town liked Mr Bingley, and he often visited Jane. But his sisters thought the Bennets were not good enough for their brother.",
        keys: [{ w: "gustaba", en: "liked" }, { w: "frecuentemente", en: "often" }, { w: "hermanas", en: "sisters" }],
      },
      C1C2: {
        text: "La admiración de Bingley por Jane crecía con cada encuentro, y el sereno carácter de ella la correspondía de buen grado. Sus hermanas, en cambio, miraban a los Bennet con velado desdén. Tramaron empujarlo hacia una alianza más ilustre.",
        translation: "Bingley's admiration for Jane grew with every meeting, and her serene temper gladly met it. His sisters, however, regarded the Bennets' connections with veiled disdain. They schemed to steer him toward a grander alliance.",
        keys: [{ w: "admiración", en: "admiration" }, { w: "desdén", en: "disdain" }, { w: "tramaron", en: "schemed" }],
      },
    },
  },
  {
    art: "umbrella", bg: "#5b6fa8",
    text: {
      A1A2: {
        text: "Llovió, y Jane se puso muy enferma y tuvo que quedarse en Netherfield.",
        translation: "It rained, and Jane got very ill and had to stay at Netherfield.",
        keys: [{ w: "llovió", en: "rained" }, { w: "enferma", en: "ill" }, { w: "quedarse", en: "stay" }],
      },
      B1B2: {
        text: "La señora Bennet envió a Jane a Netherfield a caballo, esperando lluvia. Llovió mucho, y Jane se puso enferma y tuvo que quedarse allí.",
        translation: "Mrs Bennet sent Jane to Netherfield on a horse, hoping for rain. It rained hard, and Jane became ill and had to stay there.",
        keys: [{ w: "caballo", en: "horse" }, { w: "llovió", en: "rained" }, { w: "enferma", en: "ill" }],
      },
      C1C2: {
        text: "La señora Bennet envió a Jane a Netherfield a caballo, anticipando la lluvia. El aguacero cumplió su deseo, y Jane llegó febril. Se vio obligada, para secreta satisfacción de su madre, a quedarse como huésped enferma.",
        translation: "Mrs Bennet sent Jane to Netherfield on horseback, anticipating rain. The downpour obliged her, and Jane arrived feverish. She was compelled, much to her mother's secret satisfaction, to remain as an invalid guest.",
        keys: [{ w: "anticipando", en: "anticipating" }, { w: "febril", en: "feverish" }, { w: "obligada", en: "compelled" }],
      },
    },
  },
  {
    art: "boot", bg: "#8cc2a0",
    text: {
      A1A2: {
        text: "Elizabeth estaba preocupada, así que caminó tres millas para ver a Jane.",
        translation: "Elizabeth was worried, so she walked three miles to see Jane.",
        keys: [{ w: "preocupada", en: "worried" }, { w: "caminó", en: "walked" }, { w: "millas", en: "miles" }],
      },
      B1B2: {
        text: "Elizabeth estaba preocupada por su hermana, así que caminó tres millas por campos mojados. Su vestido estaba sucio, pero el señor Darcy notó sus ojos brillantes.",
        translation: "Elizabeth was worried about her sister, so she walked three miles across wet fields. Her dress was dirty, but Mr Darcy noticed her bright eyes.",
        keys: [{ w: "preocupada", en: "worried" }, { w: "sucio", en: "dirty" }, { w: "brillantes", en: "bright" }],
      },
      C1C2: {
        text: "Alarmada por su hermana, Elizabeth caminó tres millas entre el barro hasta Netherfield. La señorita Bingley se burló de su desaliño. Darcy, sin embargo, se sintió sorprendido por el vigor que el ejercicio había dado a sus ojos.",
        translation: "Alarmed for her sister, Elizabeth tramped three miles through mud to Netherfield. Miss Bingley sneered at her dishevelment. Darcy, however, found himself struck by the vigour that exercise had lent her eyes.",
        keys: [{ w: "alarmada", en: "alarmed" }, { w: "burló", en: "sneered" }, { w: "vigor", en: "vigour" }],
      },
    },
  },
];
