#!/usr/bin/env bash
# Joins supabase/migrations/*.sql, in order, into supabase/setup.sql: the one file
# pasted into a new project's SQL editor. Run after adding a migration; a test
# fails if the two drift apart.
set -euo pipefail
cd "$(dirname "$0")/.."
out=supabase/setup.sql
{
  echo "-- ReadFluent database setup. GENERATED by scripts/build-setup-sql.sh from"
  echo "-- supabase/migrations/*.sql - edit those, not this file."
  echo "-- Paste the whole file into Supabase -> SQL Editor and press Run, once."
  for f in supabase/migrations/*.sql; do
    echo
    echo "-- ===== $(basename "$f") ====="
    cat "$f"
  done
} > "$out"
echo "wrote $out"
