#!/usr/bin/env node
// Writes components/mascot/wardrobe.ts: an import for every wardrobe picture in components/mascot/pluto
// (acc-<item>-<base>.webp and pet-<name>.webp, rendered by scripts/mascot/wardrobe.mjs), so the app finds them.
//   node scripts/mascot/wardrobe-index.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const DIR = path.join(ROOT, "components/mascot/pluto");
const BASES = ["hello-base", "reading", "cheer-base", "sleepy", "ready"];
const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".webp")).sort();
const ident = (f) => f.replace(/\.webp$/, "").replace(/[^a-z0-9]+(.)/g, (_, c) => c.toUpperCase());
const acc = {};
const pets = {};
const imports = [];
for (const f of files) {
  const m = /^acc-([a-z]+)-(.+)\.webp$/.exec(f);
  const p = /^pet-([a-z]+)\.webp$/.exec(f);
  if (m && BASES.includes(m[2])) { (acc[m[1]] ??= {})[m[2]] = ident(f); imports.push(f); }
  else if (p) { pets[p[1]] = ident(f); imports.push(f); }
}
const out = [
  "// What Pluto can wear, as rendered pictures (scripts/mascot/wardrobe.mjs). GENERATED by scripts/mascot/wardrobe-index.mjs.",
  ...imports.map((f) => `import ${ident(f)} from "./pluto/${f}";`),
  "",
  "export type Img = string | { src: string };",
  'export type Base = "hello-base" | "reading" | "cheer-base" | "sleepy" | "ready";',
  `export const ACCESSORY: Record<string, Partial<Record<Base, Img>>> = {${Object.entries(acc).map(([k, v]) => `\n  ${k}: { ${Object.entries(v).map(([b, id]) => `"${b}": ${id}`).join(", ")} },`).join("")}\n};`,
  `export const PETS: Record<string, Img> = {${Object.entries(pets).map(([k, id]) => `\n  ${k}: ${id},`).join("")}\n};`,
  "",
].join("\n");
fs.writeFileSync(path.join(ROOT, "components/mascot/wardrobe.ts"), out);
console.log(`wardrobe.ts: ${Object.keys(acc).length} accessories, ${Object.keys(pets).length} pets`);
