// What Pluto can wear, as rendered pictures (scripts/mascot/wardrobe.mjs). GENERATED by scripts/mascot/wardrobe-index.mjs.

export type Img = string | { src: string };
export type Base = "hello-base" | "reading" | "cheer-base" | "sleepy" | "ready";
export const ACCESSORY: Record<string, Partial<Record<Base, Img>>> = {
};
export const PETS: Record<string, Img> = {
};
