// What Pluto can wear, as rendered pictures (scripts/mascot/wardrobe.mjs). GENERATED by scripts/mascot/wardrobe-index.mjs.
import accBeanieCheerBase from "./pluto/acc-beanie-cheer-base.webp";
import accBeanieHelloBase from "./pluto/acc-beanie-hello-base.webp";
import accBeanieReading from "./pluto/acc-beanie-reading.webp";
import accBeanieReady from "./pluto/acc-beanie-ready.webp";
import accBeanieSleepy from "./pluto/acc-beanie-sleepy.webp";
import accCrownCheerBase from "./pluto/acc-crown-cheer-base.webp";
import accCrownHelloBase from "./pluto/acc-crown-hello-base.webp";
import accCrownReading from "./pluto/acc-crown-reading.webp";
import accCrownReady from "./pluto/acc-crown-ready.webp";
import accCrownSleepy from "./pluto/acc-crown-sleepy.webp";
import accHeadphonesCheerBase from "./pluto/acc-headphones-cheer-base.webp";
import accHeadphonesHelloBase from "./pluto/acc-headphones-hello-base.webp";
import accHeadphonesReading from "./pluto/acc-headphones-reading.webp";
import accHeadphonesReady from "./pluto/acc-headphones-ready.webp";
import accHeadphonesSleepy from "./pluto/acc-headphones-sleepy.webp";
import accPartyCheerBase from "./pluto/acc-party-cheer-base.webp";
import accPartyHelloBase from "./pluto/acc-party-hello-base.webp";
import accPartyReading from "./pluto/acc-party-reading.webp";
import accPartyReady from "./pluto/acc-party-ready.webp";
import accPartySleepy from "./pluto/acc-party-sleepy.webp";
import accShadesCheerBase from "./pluto/acc-shades-cheer-base.webp";
import accShadesHelloBase from "./pluto/acc-shades-hello-base.webp";
import accShadesReading from "./pluto/acc-shades-reading.webp";
import accShadesReady from "./pluto/acc-shades-ready.webp";
import accShadesSleepy from "./pluto/acc-shades-sleepy.webp";
import accWizardCheerBase from "./pluto/acc-wizard-cheer-base.webp";
import accWizardHelloBase from "./pluto/acc-wizard-hello-base.webp";
import accWizardReading from "./pluto/acc-wizard-reading.webp";
import accWizardReady from "./pluto/acc-wizard-ready.webp";
import accWizardSleepy from "./pluto/acc-wizard-sleepy.webp";
import petComet from "./pluto/pet-comet.webp";
import petMoon from "./pluto/pet-moon.webp";
import petRobodog from "./pluto/pet-robodog.webp";
import petUfo from "./pluto/pet-ufo.webp";

export type Img = string | { src: string };
export type Base = "hello-base" | "reading" | "cheer-base" | "sleepy" | "ready";
export const ACCESSORY: Record<string, Partial<Record<Base, Img>>> = {
  beanie: { "cheer-base": accBeanieCheerBase, "hello-base": accBeanieHelloBase, "reading": accBeanieReading, "ready": accBeanieReady, "sleepy": accBeanieSleepy },
  crown: { "cheer-base": accCrownCheerBase, "hello-base": accCrownHelloBase, "reading": accCrownReading, "ready": accCrownReady, "sleepy": accCrownSleepy },
  headphones: { "cheer-base": accHeadphonesCheerBase, "hello-base": accHeadphonesHelloBase, "reading": accHeadphonesReading, "ready": accHeadphonesReady, "sleepy": accHeadphonesSleepy },
  party: { "cheer-base": accPartyCheerBase, "hello-base": accPartyHelloBase, "reading": accPartyReading, "ready": accPartyReady, "sleepy": accPartySleepy },
  shades: { "cheer-base": accShadesCheerBase, "hello-base": accShadesHelloBase, "reading": accShadesReading, "ready": accShadesReady, "sleepy": accShadesSleepy },
  wizard: { "cheer-base": accWizardCheerBase, "hello-base": accWizardHelloBase, "reading": accWizardReading, "ready": accWizardReady, "sleepy": accWizardSleepy },
};
export const PETS: Record<string, Img> = {
  comet: petComet,
  moon: petMoon,
  robodog: petRobodog,
  ufo: petUfo,
};
